#!/bin/bash

# Model Creator Git Setup Script
# This script helps you set up the Git repository for your domain models

echo "🚀 Model Creator Git Setup"
echo "=========================="
echo

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "❌ Git repository not found. Please run 'git init' first."
    exit 1
fi

echo "✅ Git repository detected"

# Check if remote origin exists
if git remote get-url origin > /dev/null 2>&1; then
    echo "✅ Remote origin already configured: $(git remote get-url origin)"
else
    echo "🔧 Adding remote origin..."
    git remote add origin git@github.com:Hienfeld/insurance-domain-models.git
    echo "✅ Remote origin added: git@github.com:Hienfeld/insurance-domain-models.git"
fi

# Create necessary directories
echo "📁 Creating directory structure..."
mkdir -p models
mkdir -p output
mkdir -p diagrams
mkdir -p logs
echo "✅ Directories created: models/, output/, diagrams/, logs/"

# Create initial README if it doesn't exist
if [ ! -f "README.md" ]; then
    echo "📝 Creating README.md..."
    cat > README.md << EOF
# Insurance Domain Models

SIVI AFD 2.0 compliant domain models for insurance industry.

## Structure

- \`models/\` - Domain model JSON files
- \`diagrams/\` - Generated UML diagrams (Mermaid/PlantUML)
- \`output/\` - Additional generated files
- \`docs/\` - Documentation

## Usage

\`\`\`bash
# Create a new model
npm run cli create "Motor Insurance Model"

# Generate diagrams
npm run cli diagram models/motor-insurance.model.json

# Sync with Confluence
npm run cli sync
\`\`\`

## Configuration

Copy \`config.template.json\` to \`.model-creator.json\` and update with your settings.

---

Generated by @hienfeld/model-creator
EOF
    echo "✅ README.md created"
fi

# Stage and commit initial files
echo "📦 Staging initial files..."
git add .gitignore README.md config.template.json package.json

if git diff --staged --quiet; then
    echo "ℹ️  No changes to commit"
else
    echo "💾 Committing initial setup..."
    git commit -m "Initial setup: Model Creator project structure

- Added .gitignore for Node.js and Model Creator files
- Created README.md with project overview
- Added configuration template
- Set up directory structure for models and diagrams"
    echo "✅ Initial commit created"
fi

echo
echo "🎉 Git setup complete!"
echo
echo "Next steps:"
echo "1. Copy config.template.json to .model-creator.json"
echo "2. Update .model-creator.json with your GitHub token and Confluence settings"
echo "3. Run: git push -u origin main (to push to GitHub)"
echo "4. Start creating models with: npm run cli create \"Your Model Name\""
echo
